site_name: AAW Developer Docs
site_description: Developer documentation for the AAW Platform

theme:
  name: material
  palette:
    primary: yellow
    accent: blue
nav:
  - Features:
    - Overview: features/index.md
    - Object Storage:
      - S3Proxy and S3 Explorer: features/object-storage/s3proxy.md
      - Blob CSI: features/object-storage/blobcsi.md
    - Networking:
      - Cloud Main Connectivity: features/networking/cloud-main-connectivity.md
    - Data Virtualization: features/data-virtualization/trino.md
    - RBAC:
      - Non-Employee RBAC: features/rbac/non-employee-rbac.md
  - Resources:
    - Overview: resources/index.md
    - Developer Tools: developer-tools.md
